global using Microsoft.EntityFrameworkCore;
global using MediatR;
global using AutoMapper;
global using System.Text.Json;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Identity;
global using System.Security.Claims;
global using Microsoft.Extensions.Options;